# Generated by Django 2.2.7 on 2020-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emotions',
            field=models.CharField(default=0, max_length=700),
            preserve_default=False,
        ),
    ]
