# Generated by Django 2.2.7 on 2020-11-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leo', '0002_user_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='after',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='before',
            field=models.CharField(default=[0], max_length=100),
            preserve_default=False,
        ),
    ]
