# Generated by Django 2.2.7 on 2021-01-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leo', '0003_auto_20201127_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prolific',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
